apiVersion: v1
kind: Secret
metadata:
  name: finvista-secrets
  namespace: finvista
type: Opaque
data:
  GEMINI_API_KEY: QVEuQWI4Uk42TGpfbG1Cc2EzZTBnU1lTQ21NUzg2b1ZEMzVtdlBoYUJ6QlJvS2llM0lDMmc=
  GROQ_API_KEY: Z3NrX2VyQ2pqQVBGWXlMbzFrZXFrMlFxV0dkeWIzRllIZDdvVE1HQ0o3UnR0aXBsVU1xcGVUTnY=
